version: '3.8'

services:
  mongodb:
    container_name: mongodb
    image: mongo:4.4.14-focal
    env_file:
      - ./mongodb.env
    volumes:
      - ./mongodbdisk:/data/db
    ports:
      - 27017:27017
  mongo-express:
    container_name: mongoexpress
    image: mongo-express:1.0.0-alpha.4
    env_file:
      - ./mongo-express.env
    ports:
      - 7000:8081
    depends_on:
      - mongodb
  tomcat:
    container_name: tomcat4mongo
    image: tomcat:9.0.56-jre17-temurin-focal
    env_file:
      - ./tomcat4mongo.env
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    volumes:
      - ./webapps/spbootgradle.war:/usr/local/tomcat/webapps/spbootgradlemongo.war


networks:
  default:
    name: mongodb_network
